nucleos_user:
    db_driver: orm
    firewall_name: main
    from_email: '%env(MAIL_SENDER)%'
    user_class: 'App\Entity\User'
    group:
        group_class: 'App\Entity\Group'
    loggedin:
        route: 'home' # Redirect route after login
    resetting:
        from_email:   '%env(MAIL_SENDER)%'
