<?php

namespace ContainerUEpCXjx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNucleosUser_UserProvider_UsernameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nucleos_user.user_provider.username' shared service.
     *
     * @return \Nucleos\UserBundle\Security\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'security-core'.\DIRECTORY_SEPARATOR.'User'.\DIRECTORY_SEPARATOR.'UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nucleos'.\DIRECTORY_SEPARATOR.'user-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Security'.\DIRECTORY_SEPARATOR.'UserProvider.php';

        return $container->privates['nucleos_user.user_provider.username'] = new \Nucleos\UserBundle\Security\UserProvider(($container->services['Nucleos\\UserBundle\\Model\\UserManager'] ?? $container->load('getUserManagerService')));
    }
}
