<?php

namespace ContainerUEpCXjx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNucleosUser_MailerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'nucleos_user.mailer' shared service.
     *
     * @return \Nucleos\UserBundle\Mailer\SimpleResettingMailer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nucleos'.\DIRECTORY_SEPARATOR.'user-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Mailer'.\DIRECTORY_SEPARATOR.'ResettingMailer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nucleos'.\DIRECTORY_SEPARATOR.'user-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Mailer'.\DIRECTORY_SEPARATOR.'SimpleResettingMailer.php';

        return $container->services['nucleos_user.mailer'] = new \Nucleos\UserBundle\Mailer\SimpleResettingMailer(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->services['translator'] ?? $container->getTranslatorService()), ($container->services['router'] ?? $container->getRouterService()), $container->getEnv('MAIL_SENDER'));
    }
}
