<?php

namespace ContainerUEpCXjx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNucleosUser_Util_UserManipulator_SimpleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'nucleos_user.util.user_manipulator.simple' shared service.
     *
     * @return \Nucleos\UserBundle\Util\SimpleUserManipulator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nucleos'.\DIRECTORY_SEPARATOR.'user-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'UserManipulator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nucleos'.\DIRECTORY_SEPARATOR.'user-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'SimpleUserManipulator.php';

        return $container->privates['nucleos_user.util.user_manipulator.simple'] = new \Nucleos\UserBundle\Util\SimpleUserManipulator(($container->services['Nucleos\\UserBundle\\Model\\UserManager'] ?? $container->load('getUserManagerService')), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
