<?php

namespace ContainerUEpCXjx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResettingListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nucleos\UserBundle\EventListener\ResettingListener' shared service.
     *
     * @return \Nucleos\UserBundle\EventListener\ResettingListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nucleos'.\DIRECTORY_SEPARATOR.'user-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'ResettingListener.php';

        return $container->privates['Nucleos\\UserBundle\\EventListener\\ResettingListener'] = new \Nucleos\UserBundle\EventListener\ResettingListener(($container->services['router'] ?? $container->getRouterService()), 86400);
    }
}
