<?php

namespace ContainerQhTl2I1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V0XCHKSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.v0XCHKS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.v0XCHKS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
            'tokenGenerator' => ['services', 'Nucleos\\UserBundle\\Util\\TokenGenerator', 'getTokenGeneratorService', true],
        ], [
            'doctrine' => '?',
            'mailer' => '?',
            'tokenGenerator' => '?',
        ]);
    }
}
