<?php

namespace ContainerQhTl2I1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLastLoginListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Nucleos\UserBundle\EventListener\LastLoginListener' shared service.
     *
     * @return \Nucleos\UserBundle\EventListener\LastLoginListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nucleos'.\DIRECTORY_SEPARATOR.'user-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'LastLoginListener.php';

        return $container->privates['Nucleos\\UserBundle\\EventListener\\LastLoginListener'] = new \Nucleos\UserBundle\EventListener\LastLoginListener(($container->services['Nucleos\\UserBundle\\Model\\UserManager'] ?? $container->load('getUserManagerService')));
    }
}
