<?php

namespace ContainerQhTl2I1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRequestResetActionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Nucleos\UserBundle\Action\RequestResetAction' shared service.
     *
     * @return \Nucleos\UserBundle\Action\RequestResetAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'nucleos'.\DIRECTORY_SEPARATOR.'user-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Action'.\DIRECTORY_SEPARATOR.'RequestResetAction.php';

        return $container->services['Nucleos\\UserBundle\\Action\\RequestResetAction'] = new \Nucleos\UserBundle\Action\RequestResetAction(($container->privates['twig'] ?? $container->getTwigService()), ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService')), ($container->services['router'] ?? $container->getRouterService()));
    }
}
