<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQhTl2I1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQhTl2I1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQhTl2I1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQhTl2I1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQhTl2I1\App_KernelDevDebugContainer([
    'container.build_hash' => 'QhTl2I1',
    'container.build_id' => '5e774eaf',
    'container.build_time' => 1670448711,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQhTl2I1');
